
import java.awt.Color;
import javax.swing.JOptionPane;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author gvji5
 */
public class jfrmInicio extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(jfrmInicio.class.getName());

    /**
     * Creates new form jfrmInicio
     */
    public jfrmInicio() {
        initComponents();
        this.setTitle("MotherBoard");
        this.setLocationRelativeTo(null);
        this.setResizable(false);
        this.setSize(500,450);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuItem1 = new javax.swing.JMenuItem();
        jMenuItem14 = new javax.swing.JMenuItem();
        jPanel1 = new javax.swing.JPanel();
        jlblNomePieza = new javax.swing.JLabel();
        jlblPieza = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenuItem2 = new javax.swing.JMenuItem();
        jMenuItem3 = new javax.swing.JMenuItem();
        jMenuItem4 = new javax.swing.JMenuItem();
        jMenu3 = new javax.swing.JMenu();
        jMenuItem5 = new javax.swing.JMenuItem();
        jMenuItem6 = new javax.swing.JMenuItem();
        jMenuItem21 = new javax.swing.JMenuItem();
        jMenuItem7 = new javax.swing.JMenuItem();
        jMenuItem8 = new javax.swing.JMenuItem();
        jMenuItem9 = new javax.swing.JMenuItem();
        jMenuItem10 = new javax.swing.JMenuItem();
        jMenuItem11 = new javax.swing.JMenuItem();
        jMenuItem12 = new javax.swing.JMenuItem();
        jMenuItem13 = new javax.swing.JMenuItem();
        jMenuItem15 = new javax.swing.JMenuItem();
        jMenuItem16 = new javax.swing.JMenuItem();
        jMenuItem17 = new javax.swing.JMenuItem();
        jMenuItem18 = new javax.swing.JMenuItem();
        jMenuItem19 = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        jMenuItem22 = new javax.swing.JMenuItem();
        jMenuItem23 = new javax.swing.JMenuItem();

        jMenuItem1.setText("jMenuItem1");

        jMenuItem14.setText("jMenuItem14");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(153, 255, 204));

        jlblNomePieza.setBackground(new java.awt.Color(0, 0, 204));
        jlblNomePieza.setFont(new java.awt.Font("Serif", 0, 24)); // NOI18N
        jlblNomePieza.setForeground(new java.awt.Color(0, 0, 153));
        jlblNomePieza.setText("Componentes PC");

        jlblPieza.setFont(new java.awt.Font("Segoe UI", 0, 3)); // NOI18N
        jlblPieza.setText(".");
        jlblPieza.setToolTipText("");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jlblPieza, javax.swing.GroupLayout.PREFERRED_SIZE, 520, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jlblNomePieza, javax.swing.GroupLayout.PREFERRED_SIZE, 344, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(57, 57, 57)))
                .addGap(0, 47, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(jlblNomePieza)
                .addGap(18, 18, 18)
                .addComponent(jlblPieza, javax.swing.GroupLayout.DEFAULT_SIZE, 264, Short.MAX_VALUE)
                .addContainerGap())
        );

        jMenu1.setText("Archivo");

        jMenuItem2.setText("Abrir");
        jMenuItem2.addActionListener(this::jMenuItem2ActionPerformed);
        jMenu1.add(jMenuItem2);

        jMenuItem3.setText("Guardar");
        jMenuItem3.addActionListener(this::jMenuItem3ActionPerformed);
        jMenu1.add(jMenuItem3);

        jMenuItem4.setText("Salir");
        jMenuItem4.addActionListener(this::jMenuItem4ActionPerformed);
        jMenu1.add(jMenuItem4);

        jMenuBar1.add(jMenu1);

        jMenu3.setText("Componentes del PC");

        jMenuItem5.setText("Motherboard ");
        jMenuItem5.addActionListener(this::jMenuItem5ActionPerformed);
        jMenu3.add(jMenuItem5);

        jMenuItem6.setText("Procesador ");
        jMenuItem6.addActionListener(this::jMenuItem6ActionPerformed);
        jMenu3.add(jMenuItem6);

        jMenuItem21.setText("Memoria RAM");
        jMenuItem21.addActionListener(this::jMenuItem21ActionPerformed);
        jMenu3.add(jMenuItem21);

        jMenuItem7.setText("Disco Duro (HDD) ");
        jMenuItem7.addActionListener(this::jMenuItem7ActionPerformed);
        jMenu3.add(jMenuItem7);

        jMenuItem8.setText("Unidad SSD ");
        jMenuItem8.addActionListener(this::jMenuItem8ActionPerformed);
        jMenu3.add(jMenuItem8);

        jMenuItem9.setText("Fuente de Poder");
        jMenuItem9.addActionListener(this::jMenuItem9ActionPerformed);
        jMenu3.add(jMenuItem9);

        jMenuItem10.setText("Tarjeta de Video (GPU) ");
        jMenuItem10.addActionListener(this::jMenuItem10ActionPerformed);
        jMenu3.add(jMenuItem10);

        jMenuItem11.setText("Tarjeta de Red ");
        jMenuItem11.addActionListener(this::jMenuItem11ActionPerformed);
        jMenu3.add(jMenuItem11);

        jMenuItem12.setText("Cooler del Procesador ");
        jMenuItem12.addActionListener(this::jMenuItem12ActionPerformed);
        jMenu3.add(jMenuItem12);

        jMenuItem13.setText("Ventilador del Gabinete ");
        jMenuItem13.addActionListener(this::jMenuItem13ActionPerformed);
        jMenu3.add(jMenuItem13);

        jMenuItem15.setText("Tarjeta de Sonido ");
        jMenuItem15.addActionListener(this::jMenuItem15ActionPerformed);
        jMenu3.add(jMenuItem15);

        jMenuItem16.setText("Batería CMOS ");
        jMenuItem16.addActionListener(this::jMenuItem16ActionPerformed);
        jMenu3.add(jMenuItem16);

        jMenuItem17.setText("Cable SATA");
        jMenuItem17.addActionListener(this::jMenuItem17ActionPerformed);
        jMenu3.add(jMenuItem17);

        jMenuItem18.setText("Cable de Alimentación ");
        jMenuItem18.addActionListener(this::jMenuItem18ActionPerformed);
        jMenu3.add(jMenuItem18);

        jMenuItem19.setText("BIOS / UEFI ");
        jMenuItem19.addActionListener(this::jMenuItem19ActionPerformed);
        jMenu3.add(jMenuItem19);

        jMenuBar1.add(jMenu3);

        jMenu2.setText("Ayuda");

        jMenuItem22.setText("Acerca del Programa");
        jMenuItem22.addActionListener(this::jMenuItem22ActionPerformed);
        jMenu2.add(jMenuItem22);

        jMenuItem23.setText("Créditos");
        jMenuItem23.addActionListener(this::jMenuItem23ActionPerformed);
        jMenu2.add(jMenuItem23);

        jMenuBar1.add(jMenu2);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jMenuItem4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem4ActionPerformed
        int msg=JOptionPane. showConfirmDialog(null, "Desea Salir del Software");
if (msg == 0)
System. exit (0) ;
    }//GEN-LAST:event_jMenuItem4ActionPerformed

    private void jMenuItem2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem2ActionPerformed
        JOptionPane. showMessageDialog(this, "Funcionalidad Abrir") ;
    }//GEN-LAST:event_jMenuItem2ActionPerformed

    private void jMenuItem3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem3ActionPerformed
        JOptionPane. showMessageDialog(this, "Funcionalidad Guardar");
    }//GEN-LAST:event_jMenuItem3ActionPerformed

    private void jMenuItem6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem6ActionPerformed
        jlblPieza.setText("");
    jlblNomePieza.setText("Procesador");
    javax.swing.ImageIcon iconoOriginal = new javax.swing.ImageIcon(getClass().getResource("/image/cpu.png"));
    java.awt.Image imagenRedimensionada = iconoOriginal.getImage().getScaledInstance(400, 250, java.awt.Image.SCALE_SMOOTH);
    jlblPieza.setIcon(new javax.swing.ImageIcon(imagenRedimensionada));
    }//GEN-LAST:event_jMenuItem6ActionPerformed

    private void jMenuItem18ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem18ActionPerformed
        jlblPieza.setText("");
    jlblNomePieza.setText("Cable de Alimentación");
    javax.swing.ImageIcon iconoOriginal = new javax.swing.ImageIcon(getClass().getResource("/image/motherboard.png"));
    java.awt.Image imagenRedimensionada = iconoOriginal.getImage().getScaledInstance(400, 250, java.awt.Image.SCALE_SMOOTH);
    jlblPieza.setIcon(new javax.swing.ImageIcon(imagenRedimensionada));
    }//GEN-LAST:event_jMenuItem18ActionPerformed

    private void jMenuItem5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem5ActionPerformed
        jlblPieza.setText("");
    jlblNomePieza.setText("MotherBoard");
    javax.swing.ImageIcon iconoOriginal = new javax.swing.ImageIcon(getClass().getResource("/image/motherboard.png"));
    java.awt.Image imagenRedimensionada = iconoOriginal.getImage().getScaledInstance(400, 250, java.awt.Image.SCALE_SMOOTH);
    jlblPieza.setIcon(new javax.swing.ImageIcon(imagenRedimensionada));

    }//GEN-LAST:event_jMenuItem5ActionPerformed

    private void jMenuItem21ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem21ActionPerformed
       jlblPieza.setText("");
    jlblNomePieza.setText("Memoria RAM");
    javax.swing.ImageIcon iconoOriginal = new javax.swing.ImageIcon(getClass().getResource("/image/ram.png"));
    java.awt.Image imagenRedimensionada = iconoOriginal.getImage().getScaledInstance(400, 250, java.awt.Image.SCALE_SMOOTH);
    jlblPieza.setIcon(new javax.swing.ImageIcon(imagenRedimensionada));
    }//GEN-LAST:event_jMenuItem21ActionPerformed

    private void jMenuItem7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem7ActionPerformed
        jlblPieza.setText("");
    jlblNomePieza.setText("Disco Duro HDD");
    javax.swing.ImageIcon iconoOriginal = new javax.swing.ImageIcon(getClass().getResource("/image/HDD.png"));
    java.awt.Image imagenRedimensionada = iconoOriginal.getImage().getScaledInstance(400, 250, java.awt.Image.SCALE_SMOOTH);
    jlblPieza.setIcon(new javax.swing.ImageIcon(imagenRedimensionada));
    }//GEN-LAST:event_jMenuItem7ActionPerformed

    private void jMenuItem8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem8ActionPerformed
        jlblPieza.setText("");
    jlblNomePieza.setText("Unidad SSD");
    javax.swing.ImageIcon iconoOriginal = new javax.swing.ImageIcon(getClass().getResource("/image/SSD.png"));
    java.awt.Image imagenRedimensionada = iconoOriginal.getImage().getScaledInstance(400, 250, java.awt.Image.SCALE_SMOOTH);
    jlblPieza.setIcon(new javax.swing.ImageIcon(imagenRedimensionada));
    }//GEN-LAST:event_jMenuItem8ActionPerformed

    private void jMenuItem9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem9ActionPerformed
        jlblPieza.setText("");
    jlblNomePieza.setText("Fuente de poder");
    javax.swing.ImageIcon iconoOriginal = new javax.swing.ImageIcon(getClass().getResource("/image/fuente.png"));
    java.awt.Image imagenRedimensionada = iconoOriginal.getImage().getScaledInstance(400, 250, java.awt.Image.SCALE_SMOOTH);
    jlblPieza.setIcon(new javax.swing.ImageIcon(imagenRedimensionada));
    }//GEN-LAST:event_jMenuItem9ActionPerformed

    private void jMenuItem10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem10ActionPerformed
        jlblPieza.setText("");
    jlblNomePieza.setText("Tarjeta de Video GPU");
    javax.swing.ImageIcon iconoOriginal = new javax.swing.ImageIcon(getClass().getResource("/image/GPU.png"));
    java.awt.Image imagenRedimensionada = iconoOriginal.getImage().getScaledInstance(400, 250, java.awt.Image.SCALE_SMOOTH);
    jlblPieza.setIcon(new javax.swing.ImageIcon(imagenRedimensionada));
    }//GEN-LAST:event_jMenuItem10ActionPerformed

    private void jMenuItem11ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem11ActionPerformed
        jlblPieza.setText("");
    jlblNomePieza.setText("Tarjeta de Red");
    javax.swing.ImageIcon iconoOriginal = new javax.swing.ImageIcon(getClass().getResource("/image/Tarjeta de Red.png"));
    java.awt.Image imagenRedimensionada = iconoOriginal.getImage().getScaledInstance(400, 250, java.awt.Image.SCALE_SMOOTH);
    jlblPieza.setIcon(new javax.swing.ImageIcon(imagenRedimensionada));
    }//GEN-LAST:event_jMenuItem11ActionPerformed

    private void jMenuItem12ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem12ActionPerformed
       jlblPieza.setText("");
    jlblNomePieza.setText("Cooler Procesador");
    javax.swing.ImageIcon iconoOriginal = new javax.swing.ImageIcon(getClass().getResource("/image/cooler.png"));
    java.awt.Image imagenRedimensionada = iconoOriginal.getImage().getScaledInstance(400, 250, java.awt.Image.SCALE_SMOOTH);
    jlblPieza.setIcon(new javax.swing.ImageIcon(imagenRedimensionada));
    }//GEN-LAST:event_jMenuItem12ActionPerformed

    private void jMenuItem13ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem13ActionPerformed
        jlblPieza.setText("");
    jlblNomePieza.setText("Ventilador de Gabinete");
    javax.swing.ImageIcon iconoOriginal = new javax.swing.ImageIcon(getClass().getResource("/image/Ventilador.png"));
    java.awt.Image imagenRedimensionada = iconoOriginal.getImage().getScaledInstance(400, 250, java.awt.Image.SCALE_SMOOTH);
    jlblPieza.setIcon(new javax.swing.ImageIcon(imagenRedimensionada));
    }//GEN-LAST:event_jMenuItem13ActionPerformed

    private void jMenuItem15ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem15ActionPerformed
        jlblPieza.setText("");
    jlblNomePieza.setText("Tarjeta de Sonido");
    javax.swing.ImageIcon iconoOriginal = new javax.swing.ImageIcon(getClass().getResource("/image/Sonido.png"));
    java.awt.Image imagenRedimensionada = iconoOriginal.getImage().getScaledInstance(400, 250, java.awt.Image.SCALE_SMOOTH);
    jlblPieza.setIcon(new javax.swing.ImageIcon(imagenRedimensionada));
    }//GEN-LAST:event_jMenuItem15ActionPerformed

    private void jMenuItem16ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem16ActionPerformed
        jlblPieza.setText("");
    jlblNomePieza.setText("Bateria CMOS");
    javax.swing.ImageIcon iconoOriginal = new javax.swing.ImageIcon(getClass().getResource("/image/CMOS.png"));
    java.awt.Image imagenRedimensionada = iconoOriginal.getImage().getScaledInstance(400, 250, java.awt.Image.SCALE_SMOOTH);
    jlblPieza.setIcon(new javax.swing.ImageIcon(imagenRedimensionada));
    }//GEN-LAST:event_jMenuItem16ActionPerformed

    private void jMenuItem17ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem17ActionPerformed
       jlblPieza.setText("");
    jlblNomePieza.setText("Cable Sata");
    javax.swing.ImageIcon iconoOriginal = new javax.swing.ImageIcon(getClass().getResource("/image/SATA.png"));
    java.awt.Image imagenRedimensionada = iconoOriginal.getImage().getScaledInstance(400, 250, java.awt.Image.SCALE_SMOOTH);
    jlblPieza.setIcon(new javax.swing.ImageIcon(imagenRedimensionada));
    }//GEN-LAST:event_jMenuItem17ActionPerformed

    private void jMenuItem19ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem19ActionPerformed
        jlblPieza.setText("");
    jlblNomePieza.setText("BIOS/UEFI");
    javax.swing.ImageIcon iconoOriginal = new javax.swing.ImageIcon(getClass().getResource("/image/UEFI.png"));
    java.awt.Image imagenRedimensionada = iconoOriginal.getImage().getScaledInstance(400, 250, java.awt.Image.SCALE_SMOOTH);
    jlblPieza.setIcon(new javax.swing.ImageIcon(imagenRedimensionada));
    }//GEN-LAST:event_jMenuItem19ActionPerformed

    private void jMenuItem22ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem22ActionPerformed
      String descripcion = "💻 Componentes de PC - Guía Interactiva\n\n"
            + "Este software educativo está diseñado para ayudar a los Estudiantes\n"
            + "a identificar y conocer la función de las partes esenciales\n"
            + "que conforman una computadora, tales como la placa madre, el\n"
            + "procesador, las memorias y los sistemas de almacenamiento.\n\n"
            + "Versión: 1.0\n"
            + "Desarrollado en: Java Swing\n"
            + "Entorno: NetBeans IDE";
            
    JOptionPane.showMessageDialog(this, descripcion, "Acerca del Programa", JOptionPane.INFORMATION_MESSAGE);
    }//GEN-LAST:event_jMenuItem22ActionPerformed

    private void jMenuItem23ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem23ActionPerformed
       String creditos = "CRÉDITOS DEL PROYECTO\n\n"
            + " Desarrollador Principal:\n"
            + "   Javier Ignacio Vásquez García\n\n"
            + " Institución: Colegio Salesiano Don Bosco\n"
            + "   Bachillerato en Computación\n\n"
               +"Sección: D\n\n"
               +"Clave: 31\n\n"
            + "   Origen:\n"
            + "   Guatemala, 2026\n\n"
            + "¡Gracias por utilizar el software!";
            
    JOptionPane.showMessageDialog(this, creditos, "Créditos", JOptionPane.INFORMATION_MESSAGE);

    }//GEN-LAST:event_jMenuItem23ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new jfrmInicio().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem10;
    private javax.swing.JMenuItem jMenuItem11;
    private javax.swing.JMenuItem jMenuItem12;
    private javax.swing.JMenuItem jMenuItem13;
    private javax.swing.JMenuItem jMenuItem14;
    private javax.swing.JMenuItem jMenuItem15;
    private javax.swing.JMenuItem jMenuItem16;
    private javax.swing.JMenuItem jMenuItem17;
    private javax.swing.JMenuItem jMenuItem18;
    private javax.swing.JMenuItem jMenuItem19;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenuItem jMenuItem21;
    private javax.swing.JMenuItem jMenuItem22;
    private javax.swing.JMenuItem jMenuItem23;
    private javax.swing.JMenuItem jMenuItem3;
    private javax.swing.JMenuItem jMenuItem4;
    private javax.swing.JMenuItem jMenuItem5;
    private javax.swing.JMenuItem jMenuItem6;
    private javax.swing.JMenuItem jMenuItem7;
    private javax.swing.JMenuItem jMenuItem8;
    private javax.swing.JMenuItem jMenuItem9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel jlblNomePieza;
    private javax.swing.JLabel jlblPieza;
    // End of variables declaration//GEN-END:variables
}
